export const metadata = {
  title: '와인 상세 페이지',
  description: 'Generated by Next.js',
};

export default function WineDetailPageLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body>{children}</body>
    </html>
  );
}
